# Generated by Django 5.2.1 on 2025-05-16 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "created_at_pst",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at_utc", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
